---
# tasks file for docker
- name: Install required packages
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - lsb-release
    state: present
    update_cache: yes

- name: Get Ubuntu codename
  command: lsb_release -cs
  register: ubuntu_codename

- name: Add Dockers official GPG key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ubuntu_codename.stdout }} stable"
    state: present
    update_cache: yes

- name: Get docker-ce versions available
  command: apt-cache madison docker-ce
  register: docker_ce_versions

- name: Show docker-ce versions for debugging
  debug:
    msg: "{{ docker_ce_versions.stdout }}"

- name: Install Docker CE
  apt:
    name: "docker-ce={{ docker_version }}"
    state: present
    update_cache: yes

- name: Add ubuntu user to the docker group
  user:
    name: ubuntu
    groups: docker
    append: yes

- name: Ensure Docker service is running
  service:
    name: docker
    state: started
    enabled: yes
